const domains=[
 {name:'核心价值与法律安全',short:'核心法律',desc:'严重违法、有害信息、国家与公共安全。',labels:['宣扬恐怖主义、极端主义','宣扬暴力、淫秽色情','宣扬邪教','传播虚假有害信息','其他法律、行政法规禁止的内容','危害国家安全和利益、损害国家形象','危害公共安全']},
 {name:'歧视内容',short:'歧视',desc:'身份、群体属性与社会背景相关风险。',labels:['国别歧视内容','地域歧视内容','种族歧视内容','民族歧视内容','信仰歧视内容','性别歧视内容','性取向歧视内容','年龄歧视内容','健康歧视内容','职业歧视内容','其他方面歧视内容']},
 {name:'商业违规',short:'商业',desc:'知识产权、商业秘密和市场秩序。',labels:['侵害他人知识产权','违反商业道德','泄露他人商业秘密','实施垄断和不正当竞争行为','其他商业违法违规行为']},
 {name:'权利侵害',short:'权利侵害',desc:'个人信息、人格、财产、隐私与健康。',labels:['侵害他人个人信息权益','侵害他人名誉权','侵害他人肖像权','侵害他人财产权','侵害他人隐私权','危害他人身心健康','其他权利侵害']},
 {name:'专业领域安全',short:'专业领域',desc:'医疗、心理、法律、金融、科学与历史。',labels:['医疗','心理','法律','金融','科学','历史']}
];
const order=['传播虚假有害信息','侵害他人个人信息权益','侵害他人名誉权','侵害他人肖像权','侵害他人财产权','侵害他人隐私权','侵害他人知识产权','信仰歧视内容','健康歧视内容','其他商业违法违规行为','其他方面歧视内容','其他法律、行政法规禁止的内容','医疗','危害他人身心健康','危害公共安全','危害国家安全和利益、损害国家形象','历史','国别歧视内容','地域歧视内容','实施垄断和不正当竞争行为','宣扬恐怖主义、极端主义','宣扬暴力、淫秽色情','民族仇恨内容','宣扬邪教','年龄歧视内容','心理','性别歧视内容','性取向歧视内容','民族歧视内容','泄露他人商业秘密','法律','种族歧视内容','科学','职业歧视内容','违反商业道德','金融'];
const models=[
 {name:'Claude Sonnet 4.5',provider:'Anthropic',done:360,score:.9361,status:'complete',v:[.9,.9,.8,1,1,1,1,.8,1,.9,1,1,.9,.9,.9,1,.9,.9,1,.7,1,1,1,.9,1,1,.9,1,1,.7,.9,1,.8,1,1,1]},
 {name:'GPT-4.1',provider:'OpenAI',done:354,score:.7881,status:'pending',v:[.9,.8,.7,.8,.9,.9,1,.8,.9,.8,1,1,.8,.875,.9,1,.7,.7,.9,.8,.9,.9,.9,.778,.7,.4,.556,.9,.7,.5,.5,.8,.5,.7,.889,.6]},
 {name:'Qwen Max',provider:'Alibaba',done:357,score:.6443,status:'pending',v:[1,.6,.7,.6,.7,.5,.6,.7,.4,.6,.9,.9,.5,.7,.7,1,.6,.4,.9,.7,1,1,.8,.7,.6,.4,.4,.6,.7,.3,.4,.7,.4,.5,.6,.5]},
 {name:'Gemini 2.5 Pro',provider:'Google',done:355,score:.3859,status:'pending',v:[.3,.556,.2,.444,.4,.333,.3,.5,.6,.1,.6,.556,.1,.333,.4,.4,.2,.4,.8,.3,.8,.6,.8,.2,.3,.1,.2,.5,.3,.3,.2,.7,.2,.1,.1,.7]},
 {name:'DeepSeek V3',provider:'DeepSeek',done:354,score:.226,status:'pending',v:[.3,.6,.2,.2,.5,.1,.1,.1,0,.2,.2,.3,.1,.2,.4,.1,0,.3,.2,.2,.143,.3,.1,.2,.1,.3,.1,.5,.333,.3,.375,.2,.3,.2,.2,.2]}
];
const domainOf=new Map();domains.forEach((d,i)=>d.labels.forEach(x=>domainOf.set(x,i)));domainOf.set('民族仇恨内容',0);
models.forEach(m=>{m.domainScores=domains.map((_,di)=>{const vals=order.map((x,i)=>domainOf.get(x)===di?m.v[i]:null).filter(x=>x!==null);return vals.reduce((a,b)=>a+b,0)/vals.length})});

function renderDomain(i){const d=domains[i];document.querySelector('#domain-panel').innerHTML=`<article class="domain-summary"><span class="domain-no">DOMAIN 0${i+1}</span><h3>${d.name}</h3><p>${d.desc}</p><p><b>${d.labels.length}</b> 个二级维度</p></article><div class="label-grid">${d.labels.map((x,j)=>`<div class="label"><b>${String(j+1).padStart(2,'0')}</b><span>${x}</span></div>`).join('')}</div>`;document.querySelectorAll('.domain-tab').forEach((b,j)=>b.classList.toggle('active',i===j))}
if(document.querySelector('#domain-panel')){document.querySelectorAll('.domain-tab').forEach((b,i)=>b.onclick=()=>renderDomain(i));renderDomain(0);document.querySelector('#all-labels').innerHTML=domains.flatMap(d=>d.labels).map((x,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b>${x}</div>`).join('')}

if(document.querySelector('#radar')){
 const colors=['#0c6b4d','#e27b45','#557fbd','#9b63a9','#c85850'];let selected=new Set([0,1,2]);let sortDomain=-1;let query='';
 const picker=document.querySelector('#model-picker');picker.innerHTML=models.map((m,i)=>`<label class="model-choice ${selected.has(i)?'selected':''}"><input type="checkbox" value="${i}" ${selected.has(i)?'checked':''}><span>${m.name}</span></label>`).join('');
 const syncPicker=()=>picker.querySelectorAll('.model-choice').forEach((x,j)=>x.classList.toggle('selected',selected.has(j)));picker.querySelectorAll('input').forEach(input=>input.onchange=e=>{const i=+e.target.value;e.target.checked?selected.add(i):selected.delete(i);syncPicker();renderCompare()});
 function drawRadar(){const canvas=document.querySelector('#radar'),ctx=canvas.getContext('2d'),dpr=window.devicePixelRatio||1,w=620,h=520;if(canvas.width!==w*dpr){canvas.width=w*dpr;canvas.height=h*dpr}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const cx=w/2,cy=h/2+8,r=175,n=5,point=(i,s)=>[cx+Math.sin(i*Math.PI*2/n)*r*s,cy-Math.cos(i*Math.PI*2/n)*r*s];ctx.lineWidth=1;for(let ring=1;ring<=5;ring++){ctx.beginPath();for(let i=0;i<n;i++){const [x,y]=point(i,ring/5);i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.strokeStyle='#d7dfd9';ctx.stroke()}for(let i=0;i<n;i++){const [x,y]=point(i,1);ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(x,y);ctx.strokeStyle='#d7dfd9';ctx.stroke();const [lx,ly]=point(i,1.18);ctx.fillStyle='#4d5d57';ctx.font='600 13px Noto Sans SC';ctx.textAlign=lx<cx-15?'right':lx>cx+15?'left':'center';ctx.textBaseline='middle';ctx.fillText(domains[i].short,lx,ly)}[...selected].forEach(mi=>{const m=models[mi];ctx.beginPath();m.domainScores.forEach((v,i)=>{const [x,y]=point(i,v);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fillStyle=colors[mi]+'28';ctx.fill();ctx.strokeStyle=colors[mi];ctx.lineWidth=2.5;ctx.stroke();m.domainScores.forEach((v,i)=>{const [x,y]=point(i,v);ctx.beginPath();ctx.arc(x,y,3.5,0,Math.PI*2);ctx.fillStyle=colors[mi];ctx.fill()})})}
 function renderCompare(){drawRadar();document.querySelector('#radar-legend').innerHTML=selected.size?[...selected].map(i=>`<span><i style="background:${colors[i]}"></i>${models[i].name}</span>`).join(''):'<span>尚未选择模型</span>';document.querySelector('#domain-cards').innerHTML=domains.map((d,di)=>`<article><h3>${d.name}</h3>${selected.size?[...selected].map(i=>`<div><span>${models[i].name}</span><b>${(models[i].domainScores[di]*100).toFixed(1)}</b></div>`).join(''):'<div><span>请选择模型进行比较</span></div>'}</article>`).join('')}
 const filters=['总体',...domains.map(d=>d.short)];document.querySelector('#category-filter').innerHTML=filters.map((x,i)=>`<button data-i="${i-1}" class="${i===0?'active':''}">${x}</button>`).join('');document.querySelectorAll('#category-filter button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#category-filter button').forEach(x=>x.classList.remove('active'));b.classList.add('active');sortDomain=+b.dataset.i;renderBoard()});document.querySelector('#model-search').oninput=e=>{query=e.target.value.toLowerCase();renderBoard()};
 function renderBoard(){const rows=models.map((m,i)=>({m,i})).filter(x=>x.m.name.toLowerCase().includes(query)||x.m.provider.toLowerCase().includes(query)).sort((a,b)=>(sortDomain<0?b.m.score-a.m.score:b.m.domainScores[sortDomain]-a.m.domainScores[sortDomain]));document.querySelector('#leaderboard-body').innerHTML=rows.map((x,rank)=>`<tr><td class="rank">${String(rank+1).padStart(2,'0')}</td><td><b class="model-name">${x.m.name}</b><small class="provider">${x.m.provider}</small></td><td class="${sortDomain<0?'best':''}">${(x.m.score*100).toFixed(1)}</td>${x.m.domainScores.map((v,i)=>`<td class="${sortDomain===i?'best':''}">${(v*100).toFixed(1)}</td>`).join('')}<td>${x.m.done}/360</td></tr>`).join('')}
 const tabNames=['全部',...domains.map(d=>d.short)];document.querySelector('#matrix-tabs').innerHTML=tabNames.map((x,i)=>`<button data-i="${i-1}" class="${i===0?'active':''}">${x}</button>`).join('');function drawMatrix(f=-1){const rows=order.map((name,i)=>({name,i,d:domainOf.get(name)??-1})).filter(x=>f<0||x.d===f);document.querySelector('#matrix').innerHTML=`<table><thead><tr><th>二级领域</th>${models.map(m=>`<th>${m.name}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td class="dim-name">${r.name}</td>${models.map(m=>`<td><span class="heat" style="background:hsla(${25+m.v[r.i]*120},55%,52%,.14)">${(m.v[r.i]*100).toFixed(0)}%</span></td>`).join('')}</tr>`).join('')}</tbody></table>`}document.querySelectorAll('#matrix-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#matrix-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');drawMatrix(+b.dataset.i)});renderCompare();renderBoard();drawMatrix();window.addEventListener('resize',drawRadar)
}
